name: test ci
on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
jobs:
  first-job:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: check node version
        run: node --version
      - name: check npm version
        run: npm --version
      - name: checkout code from github
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: build project assets
        run: npm run build
      - name: Upload ststic site content
        uses: actions/upload-artifact@v3
        with:
          name: ststic-site
          path: .next/
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number}}
          release_name: Release ${{ github.run_number}}
